### ISSUE TITLE
Add Parameter for GetConsoleOutput to specify which consoleoutput to retrieve

### ISSUE THREAD

**Issue by Steffx115** [null511/Jenkins.NET#15]
For a tool i am coding at the moment, i need the full console log with timestamps, but the GetConsoleOutput Method uses "consoleText" as hardcoded option, a enum parameter would be nice here

**Comment by null511** [comment]
I assume your referencing [this line](https://github.com/null511/Jenkins.NET/blob/5330fa32937cc708b6d02bc2471f46102a83be9f/Jenkins.Net/Internal/Commands/BuildOutputCommand.cs#L23).

I have started a new branch that splits `GetConsoleOutput()` into two separate methods: `GetConsoleText()` (current) and a new method `GetConsoleHtml()`, which will return 'consoleFull'. I just need to test this and then I will get back to you. Thanks for reaching out!

**Comment by null511** [comment]
Ok, so that endpoint just returns the standard html page for a build, which does _not_ include timestamp information. I'm not sure of a way to support your usage currently, without third party plugins for Jenkins.

You could wrap a custom reader/writer around the `JenkinsJobRunner` class which would allow you to buffer the output and print a timestamp before each line _of when the output was received_. To have Jenkins output the timestamp as it is printed, you will most likely need a plugin which can do the same from within Jenkins.

I can put together an example of the `JenkinsJobReader` extension if it is useful to you...
